blank_issues_enabled: true
contact_links:
  - name: Invidious Companion
    url: https://github.com/iv-org/invidious-companion/issues
    about: For issues specific to the upstream Invidious Companion server, please file them there.
