name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  release-desktop:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # usually arm64 now
          - platform: 'ubuntu-22.04'
          - platform: 'windows-latest'
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: 'tauri-app/pnpm-lock.yaml'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.46.x

      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Build invidious-companion (Deno Sidecar)
        shell: bash
        run: |
          TARGET=$(rustc -vV | sed -n 's/host: //p')
          echo "Rust Target: $TARGET"
          cd invidious-companion
          deno task compile
          cd ..
          mkdir -p tauri-app/src-tauri/binaries
          if [ "$RUNNER_OS" = "Windows" ]; then
            mv invidious-companion/invidious_companion.exe "tauri-app/src-tauri/binaries/invidious-companion-$TARGET.exe"
          else
            mv invidious-companion/invidious_companion "tauri-app/src-tauri/binaries/invidious-companion-$TARGET"
          fi

      - name: Install dependencies
        working-directory: ./tauri-app
        run: pnpm install

      - name: Build Tauri App
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          projectPath: ./tauri-app
          tagName: ${{ github.ref_name }}
          releaseName: "Release ${{ github.ref_name }}"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: false
          prerelease: false


